// Generated by scripts/generate-ui-control.mjs; do not edit.
export const UI_CONTROL_CONTRACT = {
  "version": 1,
  "product": "agentworks",
  "views": [
    {
      "id": "report",
      "label": "Dashboard",
      "target_kind": "report_tab",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "flow",
      "label": "Plan",
      "target_kind": "plan_step_id",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "costs",
      "label": "Costs",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "execution-logs",
      "label": "Execution logs",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "knowledge",
      "label": "Knowledge",
      "target_kind": "view_section",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": [
        "learnings",
        "knowledgebase",
        "database"
      ]
    },
    {
      "id": "webhooks",
      "label": "Webhooks",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "schedules",
      "label": "Schedules",
      "target_kind": "view_section",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": [
        "schedules",
        "webhooks"
      ]
    },
    {
      "id": "files",
      "label": "Files",
      "target_kind": "workspace_file_path",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "pulse",
      "label": "Pulse",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "backup",
      "label": "Backup",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "publish",
      "label": "Publish",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "notify",
      "label": "Notify",
      "actions": [
        "open",
        "expand",
        "refresh"
      ],
      "targets": [
        "run_summary",
        "pulse_review"
      ]
    },
    {
      "id": "access",
      "label": "Access",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "identity",
      "label": "Identity",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "mcp",
      "label": "Integrations",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "playbooks",
      "label": "Workflow playbooks",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "browser",
      "label": "Browser automation",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": []
    },
    {
      "id": "workshop",
      "label": "Automation",
      "target_kind": "view_section",
      "actions": [
        "open",
        "refresh"
      ],
      "targets": [
        "chats",
        "schedules",
        "triggers",
        "bots"
      ]
    }
  ]
} as const
