import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('Work Dashboard', () => {
  it('reuses the shared dashboard and database views with project-scoped data', () => {
    const source = readFileSync('src/products/work/WorkWorkspacePane.tsx', 'utf8')
    const identity = readFileSync('src/products/work/WorkIdentityPanel.tsx', 'utf8')

    expect(source).toContain("{ id: 'dashboard', label: 'Dashboard'")
    expect(source).toContain("{ id: 'database', label: 'Database'")
    expect(source).toContain('<ReportDocumentSwitcher workspacePath={workspacePath}')
    expect(source).not.toContain('documentPath="db/reports/index.html"')
    expect(source).toContain("view === 'database'")
    expect(source).toContain('sendChatMessage={async (message)')
    expect(source).toContain("From this project's dashboard:")
    expect(source).toContain('emptyIdentity={{ icon: projectIdentity?.icon, name: projectIdentity?.name || projectTitle, projectName: projectTitle }}')
    expect(source).toContain('selectedGlobalSecrets={selectedGlobalSecrets}')
    expect(identity).toContain('persistExplicitGlobalSelection')
    expect(identity).toContain('allowGlobalPromotion')
  })
})

describe('Work Setup consolidation', () => {
  it('groups Setup into Identity then Integrations with shared headers and tabs', () => {
    const source = readFileSync('src/products/work/WorkWorkspacePane.tsx', 'utf8')
    const identity = readFileSync('src/products/work/WorkIdentityPanel.tsx', 'utf8')
    const integrations = readFileSync('src/products/work/WorkIntegrationsPanel.tsx', 'utf8')
    const gating = readFileSync('src/products/work/workViewGating.ts', 'utf8')

    expect(source).toContain("{ id: 'identity', label: 'Identity'")
    expect(source).toContain("{ id: 'mcp', label: 'Integrations'")
    expect(source.indexOf("{ id: 'identity'")).toBeLessThan(source.indexOf("{ id: 'mcp'"))
    expect(source).not.toContain("{ id: 'bots'")
    expect(source).not.toContain("{ id: 'models'")
    expect(source).not.toContain("{ id: 'email'")
    expect(source).toContain("view === 'identity' && <WorkIdentityPanel")
    expect(source).toContain("view === 'mcp' && <WorkIntegrationsPanel")
    expect(source).toContain('isWorkWorkspaceViewEnabled(view, enabledPanels)')
    expect(gating).toContain("if (view === 'identity') return true")
    expect(gating).toContain("enabledPanels.has('mcp') || enabledPanels.has('skills') || enabledPanels.has('bots')")
    expect(identity).toContain("tabs={{ value: activeTab")
    expect(identity).toContain("ariaLabel: 'Identity'")
    expect(identity).toContain("{ value: 'general', label: 'General' }")
    expect(identity).toContain("{ value: 'secrets', label: 'Secrets' }")
    expect(identity).toContain("{ value: 'folders', label: 'File access' }")
    expect(identity).toContain("{ value: 'models', label: 'Models' }")
    expect(identity).toContain('onUpdateIdentity={onUpdateIdentity}')
    expect(identity).toContain('onDeleteRequest={onDeleteRequest}')
    expect(identity).toContain('hideAdd')
    expect(identity).not.toContain('Attach another folder')
    expect(identity).not.toContain('Absolute folder path')
    expect(identity).toContain('<IconUploadField')
    expect(integrations).toContain("ariaLabel: 'Integrations'")
    expect(integrations).toContain("{ value: 'apps', label: 'MCPs' }")
    expect(integrations).toContain("{ value: 'skills', label: 'Skills' }")
    expect(integrations).toContain("{ value: 'slack', label: 'Slack' }")
    expect(integrations).toContain("{ value: 'whatsapp', label: 'WhatsApp' }")
    expect(integrations).toContain("{ value: 'gmail', label: 'Gmail' }")
    expect(integrations).toContain("{ value: 'cli', label: 'Connect' }")
    expect(integrations).toContain('fixedChannel="slack"')
    expect(integrations).toContain('fixedChannel="whatsapp"')
    expect(integrations).toContain('<WorkflowEmailPanel workspacePath={workspacePath} scopeNoun="project" onAsk={onAsk} />')
    expect(integrations).toContain('className="min-h-0 flex-1 overflow-y-auto p-4"')
    expect(integrations.match(/manageOwnScroll=\{false\}/g)?.length).toBe(4)
  })
})
