package step_based_workflow

import (
	"context"
	"encoding/json"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"mcp-agent-builder-go/agent_go/pkg/orchestrator"
	"mcp-agent-builder-go/agent_go/pkg/orchestrator/agents"
	orchestrator_events "mcp-agent-builder-go/agent_go/pkg/orchestrator/events"
	mcpagent "github.com/manishiitg/mcpagent/agent"
	baseevents "github.com/manishiitg/mcpagent/events"
	loggerv2 "github.com/manishiitg/mcpagent/logger/v2"
	"github.com/manishiitg/mcpagent/mcpclient"
	"github.com/manishiitg/mcpagent/observability"

	"github.com/manishiitg/multi-llm-provider-go/llmtypes"
)

// Pre-parsed templates for code execution debugging - panics at startup if invalid
var codeExecDebuggingSystemTemplate = MustRegisterTemplate("codeExecDebuggingSystem", `# Code Execution Debugging Agent
**Context**: Analyzing run path '{{.RunPathRelative}}'
**Scope**: Debugging {{.CodeExecStepsCount}} code execution steps out of {{.TotalStepsCount}} total steps

## 🤖 ROLE
Specialized debugger for code execution steps. Your goal is to identify and fix errors related to code writing, execution, and workspace tool usage in Go code generated by execution agents.

**IMPORTANT**: Only debug the code execution steps listed in the user message. Skip any tool execution steps.

## ⚠️ CRITICAL DEBUGGING RULES (Code Execution Mode)
1. **WorkspacePath Handling**: The first CLI argument (`+"`"+`os.Args[1]`+"`"+`) MUST be the base workspace path.
   - ❌ **Error**: `+"`"+`args=["{{.WorkspacePath}}/file.json"]`+"`"+` (Passed full path as arg).
   - ✅ **Fix**: `+"`"+`args=["{{.WorkspacePath}}"]`+"`"+` and use `+"`"+`filepath.Join(os.Args[1], "file.json")`+"`"+` in code.
2. **Hardcoded Paths**: Iteration-specific paths (e.g., `+"`"+`runs/iteration-11/...`+"`"+`) must NEVER be hardcoded in Go code.
3. **Workspace Tools**: Code should use `+"`"+`workspace_tools.ReadWorkspaceFile`+"`"+` instead of standard `+"`"+`os.ReadFile`+"`"+` for managed workspace access.

## 🎯 FOCUS AREAS
1. **Workspace Tool Errors**:
   - `+"`"+`FileNotFoundError`+"`"+` or "no such file or directory": Often caused by hardcoded paths or missing dependencies.
   - `+"`"+`IsADirectoryError`+"`"+`: Code tries to read a directory as a file.
   - Format Errors: JSON/CSV parsing failures due to unexpected content.

2. **Code Execution Failures**:
   - Syntax errors or missing imports in generated Go code.
   - Runtime panics (nil pointer, out of bounds).

3. **Prerequisite Failures**:
   - Step N fails because Step N-1 output is missing or improperly formatted.

## 📋 EVIDENCE SOURCES
- **Execution Logs**: '{{.RunPathRelative}}/execution/' and '{{.RunPathRelative}}/logs/'.
- **Conversation Logs**: Look for the `+"`"+`write_code`+"`"+` tool call to see exact `+"`"+`args`+"`"+` and `+"`"+`code`+"`"+` passed.
- **Plan**: 'planning/plan.json'. Check `+"`"+`context_dependencies`+"`"+`.

---

## 🔄 WORKFLOW
1. **Analyze**: Read 'logs/' and 'execution/' files. Inspect the `+"`"+`write_code`+"`"+` call details.
2. **Diagnose**: Identify if the error is due to bad pathing, tool misuse, or plan logic.
3. **Propose**: Use 'human_feedback' to explain the issue and the fix.
4. **Fix**: After approval, update the plan steps or success criteria to prevent recurrence.

{{if .AllowedPaths}}**Allowed Paths**: {{.AllowedPaths}}{{end}}`)

var codeExecDebuggingUserTemplate = MustRegisterTemplate("codeExecDebuggingUser", `# Code Execution Debugging Task
## 📋 CONTEXT
- **Workspace**: {{.WorkspacePath}}
- **Selected Run**: {{.RunPathRelative}}
- **Code Execution Steps**: {{.CodeExecStepsCount}} out of {{.TotalStepsCount}} total steps

## 🎯 STEPS TO DEBUG
{{.CodeExecStepsSummary}}

## 📊 DATA
**Execution Summary**:
{{.ExecutionResultsSummary}}

**Current Plan**:
{{if .PlanJSON}}{{.PlanJSON}}{{else}}No plan provided.{{end}}

## 🧠 TASK
1. **ONLY** analyze the code execution steps listed above - skip tool execution steps.
2. For each code execution step, check execution logs and conversation history for errors.
3. Verify if the `+"`"+`write_code`+"`"+` arguments and path handling follow the Code Execution Mode rules.
4. Propose fixes via 'human_feedback' before modifying the plan.`)

// WorkflowCodeExecDebuggingTemplate holds template variables for code execution debugging prompts
type WorkflowCodeExecDebuggingTemplate struct {
	WorkspacePath           string
	RunPathRelative         string
	RunWorkspacePath        string
	PlanJSON                string
	ExecutionResultsSummary string
	AllowedPaths            string
	CodeExecStepsSummary    string
	CodeExecStepsCount      string
	TotalStepsCount         string
}

// WorkflowCodeExecDebuggingAgent analyzes execution logs for code execution errors
type WorkflowCodeExecDebuggingAgent struct {
	*agents.BaseOrchestratorAgent
	baseOrchestrator *orchestrator.BaseOrchestrator // Reference to base orchestrator for RequestHumanFeedback
}

// NewWorkflowCodeExecDebuggingAgent creates a new code execution debugging agent
func NewWorkflowCodeExecDebuggingAgent(config *agents.OrchestratorAgentConfig, logger loggerv2.Logger, tracer observability.Tracer, eventBridge mcpagent.AgentEventListener, baseOrchestrator *orchestrator.BaseOrchestrator) *WorkflowCodeExecDebuggingAgent {
	baseAgent := agents.NewBaseOrchestratorAgentWithEventBridge(
		config,
		logger,
		tracer,
		agents.TodoPlannerCodeExecDebuggingAgentType,
		eventBridge,
	)

	return &WorkflowCodeExecDebuggingAgent{
		BaseOrchestratorAgent: baseAgent,
		baseOrchestrator:      baseOrchestrator,
	}
}

// CodeExecDebuggingManager manages code execution debugging agent creation independently from controller
type CodeExecDebuggingManager struct {
	// Base orchestrator for common functionality
	*orchestrator.BaseOrchestrator

	// Phase LLM config (fallback)
	presetPhaseLLM *AgentLLMConfig

	// Session and workflow IDs for human feedback
	sessionID  string
	workflowID string
}

// NewCodeExecDebuggingManager creates a new CodeExecDebuggingManager
func NewCodeExecDebuggingManager(
	baseOrchestrator *orchestrator.BaseOrchestrator,
	presetPhaseLLM *AgentLLMConfig,
	sessionID string,
	workflowID string,
) *CodeExecDebuggingManager {
	return &CodeExecDebuggingManager{
		BaseOrchestrator: baseOrchestrator,
		presetPhaseLLM:   presetPhaseLLM,
		sessionID:        sessionID,
		workflowID:       workflowID,
	}
}

// createCodeExecDebuggingAgent creates and sets up a code execution debugging agent
func (cdm *CodeExecDebuggingManager) createCodeExecDebuggingAgent(ctx context.Context, workspacePath string, originalWorkspacePath string) (agents.OrchestratorAgent, error) {
	// Set folder guard paths: similar to plan improvement agent
	currentWorkspacePath := workspacePath
	learningsPath := fmt.Sprintf("%s/learnings", originalWorkspacePath)
	planningPath := fmt.Sprintf("%s/planning", originalWorkspacePath)
	knowledgebasePath := getKnowledgebasePath(originalWorkspacePath)
	runsPath := fmt.Sprintf("%s/runs", originalWorkspacePath)

	readPaths := []string{
		currentWorkspacePath, // Read execution results and logs from current workspace
		runsPath,             // Read access to all runs
		knowledgebasePath,    // Read knowledgebase folder
		learningsPath,        // Read learnings
		planningPath,         // Read plan.json
	}

	writePaths := []string{
		learningsPath, // Write access to learnings folder
		planningPath,  // Write access to plan.json (required for plan fixes)
	}

	cdm.SetWorkspacePathForFolderGuard(readPaths, writePaths)
	cdm.GetLogger().Info(fmt.Sprintf("🔍 Setting folder guard for code execution debugging agent - Read paths: %v, Write paths: %v", readPaths, writePaths))

	// Determine LLM config (use preset phase LLM only)
	var llmConfigToUse *orchestrator.LLMConfig
	if cdm.presetPhaseLLM != nil && cdm.presetPhaseLLM.Provider != "" && cdm.presetPhaseLLM.ModelID != "" {
		llmConfigToUse = &orchestrator.LLMConfig{
			Primary: orchestrator.LLMModel{
				Provider: cdm.presetPhaseLLM.Provider,
				ModelID:  cdm.presetPhaseLLM.ModelID,
			},
			Fallbacks: cdm.GetFallbacks(),
			APIKeys:   cdm.GetAPIKeys(),
		}
		cdm.GetLogger().Info(fmt.Sprintf("🔧 Using preset phase LLM for debugging: %s/%s", cdm.presetPhaseLLM.Provider, cdm.presetPhaseLLM.ModelID))
	} else {
		return nil, fmt.Errorf("no valid LLM configuration found for debugging agent: presetPhaseLLM is empty or invalid")
	}

	// Use workspace tools directly
	allTools := cdm.WorkspaceTools
	allExecutors := cdm.WorkspaceToolExecutors

	config := cdm.CreateStandardAgentConfigWithLLM("code-exec-debugging-agent", 100, agents.OutputFormatStructured, llmConfigToUse)
	config.ServerNames = []string{mcpclient.NoServers}
	config.UseCodeExecutionMode = false // Debugging agent analyzes code, doesn't execute it

	// Create wrapper function
	createAgentFunc := func(cfg *agents.OrchestratorAgentConfig, logger loggerv2.Logger, tracer observability.Tracer, eventBridge mcpagent.AgentEventListener) agents.OrchestratorAgent {
		return NewWorkflowCodeExecDebuggingAgent(cfg, logger, tracer, eventBridge, cdm.BaseOrchestrator)
	}

	// Setup agent
	agent, err := cdm.CreateAndSetupStandardAgentWithConfig(
		ctx,
		config,
		"code-exec-debugging",
		0, 0,
		"code-exec-debugging", // stepID (use phase name for phase-only agents)
		createAgentFunc,
		allTools,
		allExecutors,
		true, // overwriteSystemPrompt
	)
	if err != nil {
		return nil, fmt.Errorf("failed to create code exec debugging agent: %w", err)
	}

	return agent, nil
}

// CodeExecDebuggingOnly runs the code execution debugging analysis
func (cdm *CodeExecDebuggingManager) CodeExecDebuggingOnly(ctx context.Context, originalWorkspacePath string, runPath string) (string, error) {
	cdm.GetLogger().Info(fmt.Sprintf("🔍 Starting code execution debugging for workspace: %s", originalWorkspacePath))

	// Validate run path
	var validatedRunPath string
	var err error

	if runPath != "" {
		cdm.GetLogger().Info(fmt.Sprintf("📊 Using provided run path: %s", runPath))
		validatedRunPath, err = cdm.validateRunPath(ctx, originalWorkspacePath, runPath)
		if err != nil {
			cdm.GetLogger().Warn(fmt.Sprintf("⚠️ Provided run path validation failed: %v, falling back to user input", err))
			// Fall back to asking user
			validatedRunPath, err = cdm.requestAndValidateFullPath(ctx, originalWorkspacePath)
			if err != nil {
				return "", fmt.Errorf("failed to get validated path: %w", err)
			}
		} else {
			cdm.GetLogger().Info(fmt.Sprintf("✅ Successfully validated provided run path: %s", validatedRunPath))
		}
	} else {
		// No run path provided - request and validate full path from user via blocking human feedback
		cdm.GetLogger().Info(fmt.Sprintf("📊 Requesting full path from user for code execution debugging"))
		validatedRunPath, err = cdm.requestAndValidateFullPath(ctx, originalWorkspacePath)
		if err != nil {
			return "", fmt.Errorf("failed to get validated path: %w", err)
		}
	}

	// Set workspace paths
	cdm.SetWorkspacePath(originalWorkspacePath)
	runWorkspacePath := fmt.Sprintf("%s/%s", originalWorkspacePath, validatedRunPath)

	// Check plan
	planPath := fmt.Sprintf("%s/planning/plan.json", originalWorkspacePath)
	planExist, existingPlan, err := cdm.checkExistingPlan(ctx, planPath)
	if err != nil {
		return "", fmt.Errorf("failed to check for existing plan: %w", err)
	}
	if !planExist {
		return "", fmt.Errorf("plan.json not found at %s", planPath)
	}

	// Filter to only code execution steps
	codeExecSteps, totalSteps, err := cdm.filterCodeExecutionSteps(ctx, existingPlan, originalWorkspacePath, runWorkspacePath)
	if err != nil {
		cdm.GetLogger().Warn(fmt.Sprintf("⚠️ Failed to filter code execution steps: %v, will debug all steps", err))
	}

	// Check if there are any code execution steps to debug
	if len(codeExecSteps) == 0 {
		cdm.GetLogger().Info("ℹ️ No code execution steps found in the plan - nothing to debug")
		return fmt.Sprintf("No code execution steps found out of %d total steps. All steps use tool execution mode. Code execution debugging is not applicable for this workflow.", totalSteps), nil
	}

	// Marshal plan
	planJSONBytes, err := json.MarshalIndent(existingPlan, "", "  ")
	if err != nil {
		return "", fmt.Errorf("failed to marshal plan to JSON: %w", err)
	}

	// Summary with code execution steps info
	codeExecStepsSummary := formatCodeExecStepsSummary(codeExecSteps, totalSteps)
	executionResultsSummary := fmt.Sprintf(
		"Workspace root: %s\nSelected run folder: %s\n\n## Code Execution Steps to Debug\n%s\n\nCheck execution/ and logs/ folders for errors in these steps only.",
		originalWorkspacePath,
		validatedRunPath,
		codeExecStepsSummary,
	)

	// Create agent
	agent, err := cdm.createCodeExecDebuggingAgent(ctx, runWorkspacePath, originalWorkspacePath)
	if err != nil {
		return "", fmt.Errorf("failed to create agent: %w", err)
	}

	// Template vars
	allowedPaths := fmt.Sprintf("['planning/', 'learnings/', '%s/']", validatedRunPath)
	templateVars := map[string]string{
		"WorkspacePath":           originalWorkspacePath,
		"RunPathRelative":         validatedRunPath,
		"RunWorkspacePath":        runWorkspacePath,
		"PlanJSON":                string(planJSONBytes),
		"ExecutionResultsSummary": executionResultsSummary,
		"AllowedPaths":            allowedPaths,
		"SessionID":               cdm.sessionID,
		"WorkflowID":              cdm.workflowID,
		"CodeExecStepsSummary":    codeExecStepsSummary,
		"CodeExecStepsCount":      fmt.Sprintf("%d", len(codeExecSteps)),
		"TotalStepsCount":         fmt.Sprintf("%d", totalSteps),
	}

	// Execute
	cdm.GetLogger().Info(fmt.Sprintf("🔍 Executing code execution debugging agent..."))
	result, _, err := agent.Execute(ctx, templateVars, nil)
	if err != nil {
		return "", fmt.Errorf("agent execution failed: %w", err)
	}

	return result, nil
}

// requestAndValidateFullPath asks the user for the path via blocking human feedback and validates it has execution/ folder
// User provides paths like "iteration-11" or "iteration-11/group-7" (relative to runs/)
// Returns the full path relative to original workspace (e.g., "runs/iteration-11" or "runs/iteration-11/group-7")
func (cdm *CodeExecDebuggingManager) requestAndValidateFullPath(ctx context.Context, originalWorkspacePath string) (string, error) {
	maxAttempts := 5
	attempt := 0

	for attempt < maxAttempts {
		attempt++

		// Generate unique request ID
		requestID := fmt.Sprintf("code_exec_debugging_full_path_%d_%d", attempt, time.Now().UnixNano())

		// Ask user for the path
		var promptMessage string
		if attempt == 1 {
			promptMessage = fmt.Sprintf("Please provide the folder path to debug (relative to runs/ folder).\n\nExamples:\n- 'iteration-11' - to debug a specific iteration\n- 'iteration-11/group-7' - to debug a specific group\n\nThe path must contain an execution/ folder.\n\nThe workspace root is: %s", originalWorkspacePath)
		} else {
			promptMessage = fmt.Sprintf("The path you provided doesn't exist or doesn't contain an execution/ folder. Please provide a valid path relative to runs/ folder (attempt %d/%d).\n\nExamples: 'iteration-11', 'iteration-11/group-7'\n\nThe workspace root is: %s", attempt, maxAttempts, originalWorkspacePath)
		}

		// Request human feedback (blocking call)
		approved, userPath, err := cdm.RequestHumanFeedback(
			ctx,
			requestID,
			promptMessage,
			"",
			cdm.sessionID,
			cdm.workflowID,
		)
		if err != nil {
			return "", fmt.Errorf("failed to get path from user: %w", err)
		}

		// If user clicked Approve without providing a path, treat as cancellation
		if approved && strings.TrimSpace(userPath) == "" {
			return "", fmt.Errorf("user approved without providing a path")
		}

		// Clean up the path (remove leading/trailing spaces and slashes, remove runs/ prefix if included)
		userPath = strings.TrimSpace(userPath)
		userPath = strings.TrimPrefix(userPath, "runs/")
		userPath = strings.TrimPrefix(userPath, "/")
		userPath = strings.TrimSuffix(userPath, "/")

		if userPath == "" {
			cdm.GetLogger().Warn(fmt.Sprintf("⚠️ Empty path provided, asking again"))
			continue
		}

		// Construct full path: runs/{userPath}
		fullPath := fmt.Sprintf("%s/runs/%s", originalWorkspacePath, userPath)
		executionPath := fmt.Sprintf("%s/execution", fullPath)

		cdm.GetLogger().Info(fmt.Sprintf("🔍 Validating path: %s (full path: %s, checking execution: %s)", userPath, fullPath, executionPath))

		// First check if the base path exists
		_, err = cdm.ListWorkspaceFiles(ctx, fullPath)
		if err != nil {
			cdm.GetLogger().Warn(fmt.Sprintf("⚠️ Path validation failed: %s does not exist: %v", fullPath, err))
			continue
		}

		// Check if execution/ folder exists in this path
		files, err := cdm.ListWorkspaceFiles(ctx, executionPath)
		if err != nil {
			// execution/ folder doesn't exist
			cdm.GetLogger().Warn(fmt.Sprintf("⚠️ Path validation failed: %s does not contain an execution/ folder: %v", fullPath, err))
			continue
		}

		// Path exists and has execution/ folder
		cdm.GetLogger().Info(fmt.Sprintf("✅ Validated path: runs/%s (found %d items in execution/ folder)", userPath, len(files)))

		// Return the full path relative to original workspace (e.g., "runs/iteration-11")
		return fmt.Sprintf("runs/%s", userPath), nil
	}

	return "", fmt.Errorf("failed to get valid path after %d attempts", maxAttempts)
}

// validateRunPath validates a run path without asking the user
// runPath can be in format "runs/iteration-11", "iteration-11", or "iteration-11/group-7"
// Returns the full path relative to original workspace (e.g., "runs/iteration-11") if valid
func (cdm *CodeExecDebuggingManager) validateRunPath(ctx context.Context, originalWorkspacePath string, runPath string) (string, error) {
	// Clean up the path (remove leading/trailing spaces and slashes, remove runs/ prefix if included)
	cleanedPath := strings.TrimSpace(runPath)
	cleanedPath = strings.TrimPrefix(cleanedPath, "runs/")
	cleanedPath = strings.TrimPrefix(cleanedPath, "/")
	cleanedPath = strings.TrimSuffix(cleanedPath, "/")

	if cleanedPath == "" {
		return "", fmt.Errorf("empty run path provided")
	}

	// Construct full path: runs/{cleanedPath}
	fullPath := fmt.Sprintf("%s/runs/%s", originalWorkspacePath, cleanedPath)
	executionPath := fmt.Sprintf("%s/execution", fullPath)

	cdm.GetLogger().Info(fmt.Sprintf("🔍 Validating run path: %s (full path: %s, checking execution: %s)", cleanedPath, fullPath, executionPath))

	// First check if the base path exists
	_, err := cdm.ListWorkspaceFiles(ctx, fullPath)
	if err != nil {
		return "", fmt.Errorf("path does not exist: %s: %w", fullPath, err)
	}

	// Check if execution/ folder exists in this path
	files, err := cdm.ListWorkspaceFiles(ctx, executionPath)
	if err != nil {
		return "", fmt.Errorf("path does not contain an execution/ folder: %s: %w", fullPath, err)
	}

	// Path exists and has execution/ folder
	cdm.GetLogger().Info(fmt.Sprintf("✅ Validated run path: runs/%s (found %d items in execution/ folder)", cleanedPath, len(files)))

	// Return the full path relative to original workspace (e.g., "runs/iteration-11")
	return fmt.Sprintf("runs/%s", cleanedPath), nil
}

// checkExistingPlan checks if a plan.json file already exists
func (cdm *CodeExecDebuggingManager) checkExistingPlan(ctx context.Context, planPath string) (bool, *PlanningResponse, error) {
	cdm.GetLogger().Info(fmt.Sprintf("🔍 Checking for existing plan at %s", planPath))
	workspacePath := filepath.Dir(filepath.Dir(planPath))
	plan, err := readPlanFromFile(ctx, workspacePath, cdm.ReadWorkspaceFile)
	if err != nil {
		if strings.Contains(err.Error(), "not found") || strings.Contains(err.Error(), "no such file") {
			return false, nil, nil
		}
		return false, nil, err
	}
	return true, plan, nil
}

// CodeExecStepInfo holds information about a code execution step for debugging
type CodeExecStepInfo struct {
	StepIndex int    // 0-based index in plan
	StepID    string // Step ID from plan.json
	StepTitle string // Step title for display
	StepPath  string // Step path (e.g., "step-1", "step-3-if-true-0")
}

// filterCodeExecutionSteps filters plan steps to only include those with code execution mode enabled
// Uses existing isStepCodeExecutionModeEnabled function from plan_opt_tool_optimization_agent.go
// Returns a list of code execution step info and the total count of steps
func (cdm *CodeExecDebuggingManager) filterCodeExecutionSteps(ctx context.Context, plan *PlanningResponse, originalWorkspacePath string, runWorkspacePath string) ([]CodeExecStepInfo, int, error) {
	// Load step configurations to get original agent configs (e.g. LLM settings)
	// We pass "planning" as the configSubdir since step_config.json is always in planning/ folder for execution
	stepConfigs, err := ReadStepConfigs(ctx, cdm.BaseOrchestrator, originalWorkspacePath, runWorkspacePath, "planning")
	if err != nil {
		cdm.GetLogger().Warn(fmt.Sprintf("⚠️ Failed to read step_config.json: %v (using defaults)", err))
		stepConfigs = []StepConfig{}
	}

	// Get preset code execution mode from orchestrator
	presetCodeExecMode := cdm.GetUseCodeExecutionMode()
	cdm.GetLogger().Info(fmt.Sprintf("🔧 Preset code execution mode: %v", presetCodeExecMode))

	var codeExecSteps []CodeExecStepInfo
	totalSteps := len(plan.Steps)

	for i, step := range plan.Steps {
		stepID := step.GetID()
		// Use existing helper function to check if step uses code execution mode
		if isStepCodeExecutionModeEnabled(stepID, stepConfigs, presetCodeExecMode) {
			stepPath := fmt.Sprintf("step-%d", i+1) // 1-based step path
			codeExecSteps = append(codeExecSteps, CodeExecStepInfo{
				StepIndex: i,
				StepID:    stepID,
				StepTitle: step.GetTitle(),
				StepPath:  stepPath,
			})
			cdm.GetLogger().Info(fmt.Sprintf("✅ Step %d '%s' (ID: %s) uses code execution mode", i+1, step.GetTitle(), stepID))
		} else {
			cdm.GetLogger().Info(fmt.Sprintf("⏭️ Step %d '%s' (ID: %s) does NOT use code execution mode - skipping", i+1, step.GetTitle(), stepID))
		}

		// Also check branch steps for conditional steps
		if conditionalStep, ok := step.(*ConditionalPlanStep); ok {
			// Check true branch steps
			for j, branchStep := range conditionalStep.IfTrueSteps {
				branchStepID := branchStep.GetID()
				if isStepCodeExecutionModeEnabled(branchStepID, stepConfigs, presetCodeExecMode) {
					stepPath := fmt.Sprintf("step-%d-if-true-%d", i+1, j)
					codeExecSteps = append(codeExecSteps, CodeExecStepInfo{
						StepIndex: i,
						StepID:    branchStepID,
						StepTitle: branchStep.GetTitle(),
						StepPath:  stepPath,
					})
					cdm.GetLogger().Info(fmt.Sprintf("✅ Branch step '%s' (ID: %s) uses code execution mode", branchStep.GetTitle(), branchStepID))
				}
			}
			// Check false branch steps
			for j, branchStep := range conditionalStep.IfFalseSteps {
				branchStepID := branchStep.GetID()
				if isStepCodeExecutionModeEnabled(branchStepID, stepConfigs, presetCodeExecMode) {
					stepPath := fmt.Sprintf("step-%d-if-false-%d", i+1, j)
					codeExecSteps = append(codeExecSteps, CodeExecStepInfo{
						StepIndex: i,
						StepID:    branchStepID,
						StepTitle: branchStep.GetTitle(),
						StepPath:  stepPath,
					})
					cdm.GetLogger().Info(fmt.Sprintf("✅ Branch step '%s' (ID: %s) uses code execution mode", branchStep.GetTitle(), branchStepID))
				}
			}
		}
	}

	cdm.GetLogger().Info(fmt.Sprintf("📊 Found %d code execution steps out of %d total steps", len(codeExecSteps), totalSteps))
	return codeExecSteps, totalSteps, nil
}

// formatCodeExecStepsSummary formats the code execution steps for display in the prompt
func formatCodeExecStepsSummary(codeExecSteps []CodeExecStepInfo, totalSteps int) string {
	if len(codeExecSteps) == 0 {
		return fmt.Sprintf("No code execution steps found out of %d total steps. All steps use tool execution mode.", totalSteps)
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("Found %d code execution steps out of %d total steps:\n\n", len(codeExecSteps), totalSteps))
	for _, step := range codeExecSteps {
		sb.WriteString(fmt.Sprintf("- **%s**: %s (ID: %s)\n", step.StepPath, step.StepTitle, step.StepID))
	}
	sb.WriteString("\n**Only these steps use code execution mode and should be debugged.**")
	return sb.String()
}

// Execute implements OrchestratorAgent interface
func (agent *WorkflowCodeExecDebuggingAgent) Execute(ctx context.Context, templateVars map[string]string, conversationHistory []llmtypes.MessageContent) (string, []llmtypes.MessageContent, error) {
	// Extract variables
	workspacePath := templateVars["WorkspacePath"]
	planJSON := templateVars["PlanJSON"]
	executionResultsSummary := templateVars["ExecutionResultsSummary"]
	runPathRelative := templateVars["RunPathRelative"]
	runWorkspacePath := templateVars["RunWorkspacePath"]
	allowedPaths := templateVars["AllowedPaths"]

	templateData := WorkflowCodeExecDebuggingTemplate{
		WorkspacePath:           workspacePath,
		RunPathRelative:         runPathRelative,
		RunWorkspacePath:        runWorkspacePath,
		PlanJSON:                planJSON,
		ExecutionResultsSummary: executionResultsSummary,
		AllowedPaths:            allowedPaths,
		CodeExecStepsSummary:    templateVars["CodeExecStepsSummary"],
		CodeExecStepsCount:      templateVars["CodeExecStepsCount"],
		TotalStepsCount:         templateVars["TotalStepsCount"],
	}

	// Get base agent capabilities
	baseAgent := agent.BaseOrchestratorAgent.BaseAgent()
	var logger loggerv2.Logger
	var mcpAgent *mcpagent.Agent
	if baseAgent != nil {
		mcpAgent = baseAgent.Agent()
		if mcpAgent != nil && mcpAgent.Logger != nil {
			logger = mcpAgent.Logger
		}
	}

	// Register tools
	var readFile func(context.Context, string) (string, error)
	var writeFile func(context.Context, string, string) error
	var moveFile func(context.Context, string, string) error
	if agent.baseOrchestrator != nil {
		readFile = agent.baseOrchestrator.ReadWorkspaceFile
		writeFile = agent.baseOrchestrator.WriteWorkspaceFile
		moveFile = agent.baseOrchestrator.MoveWorkspaceFile
	}

	// Register plan modification tools
	var unlockLearningsFunc func(context.Context, string, int) error
	if agent.baseOrchestrator != nil {
		unlockLearningsFunc = createUnlockLearningsFunctionFromBase(agent.baseOrchestrator, workspacePath)
	}
	if err := registerPlanModificationTools(mcpAgent, workspacePath, logger, readFile, writeFile, moveFile, "code exec debugging agent", unlockLearningsFunc); err != nil {
		return "", nil, err
	}

	// Prepare prompts
	systemPrompt := agent.codeExecDebuggingSystemPromptProcessor(templateVars)
	userMessage := agent.codeExecDebuggingUserMessageProcessor(templateVars)

	// Execution loop
	maxIterations := 20
	iteration := 0
	currentResult := ""
	currentConversationHistory := conversationHistory
	sessionID := templateVars["SessionID"]
	workflowID := templateVars["WorkflowID"]

	// Emit start event
	if agent.baseOrchestrator != nil {
		eventBridge := agent.baseOrchestrator.GetContextAwareBridge()
		if eventBridge != nil {
			startedEvent := &orchestrator_events.OrchestratorAgentStartEvent{
				BaseEventData: baseevents.BaseEventData{
					Timestamp: time.Now(),
					Component: "orchestrator",
				},
				AgentType: "code-exec-debugging",
				AgentName: "code-exec-debugging-agent",
				Objective: "Debug code execution errors",
				InputData: templateVars,
			}
			eventBridge.HandleEvent(ctx, &baseevents.AgentEvent{
				Type:      orchestrator_events.OrchestratorAgentStart,
				Timestamp: time.Now(),
				Data:      startedEvent,
			})
		}
	}

	for iteration < maxIterations {
		iteration++
		if logger != nil {
			logger.Info(fmt.Sprintf("🔍 Code exec debugging iteration %d/%d", iteration, maxIterations))
		}

		inputProcessor := func(map[string]string) string {
			return userMessage
		}

		result, updatedConversationHistory, err := agent.ExecuteWithTemplateValidation(ctx, templateVars, inputProcessor, currentConversationHistory, templateData, systemPrompt, true)
		if err != nil {
			return "", nil, err
		}

		currentResult = result
		currentConversationHistory = updatedConversationHistory

		if agent.baseOrchestrator != nil {
			toolCalls := ExtractToolCallsFromMessages(updatedConversationHistory)
			planUpdateToolCalled := false
			for _, toolName := range toolCalls {
				if IsPlanModificationTool(toolName) || IsStepConfigModificationTool(toolName) {
					planUpdateToolCalled = true
					break
				}
			}
			if planUpdateToolCalled {
				CheckAndEmitPlanUpdateEvent(ctx, agent.baseOrchestrator, updatedConversationHistory, workspacePath, readFile)
			}
		}

		// Ask user to continue
		if iteration < maxIterations && agent.baseOrchestrator != nil {
			requestID := fmt.Sprintf("code_exec_debugging_continue_%d_%d", iteration, time.Now().UnixNano())
			approved, feedback, err := agent.baseOrchestrator.RequestHumanFeedback(
				ctx,
				requestID,
				fmt.Sprintf("Debugging iteration %d/%d complete. Approve to finish debugging, or provide feedback to continue.", iteration, maxIterations),
				currentResult,
				sessionID,
				workflowID,
			)
			if err != nil {
				break
			}
			if approved {
				break
			}
			if feedback != "" {
				userMessage = feedback
			}
		} else {
			break
		}
	}

	// Emit end event
	if agent.baseOrchestrator != nil {
		eventBridge := agent.baseOrchestrator.GetContextAwareBridge()
		if eventBridge != nil {
			completedEvent := &orchestrator_events.OrchestratorAgentEndEvent{
				BaseEventData: baseevents.BaseEventData{
					Timestamp: time.Now(),
					Component: "orchestrator",
				},
				AgentType: "code-exec-debugging",
				AgentName: "code-exec-debugging-agent",
				Objective: "Debug code execution errors",
				Result:    currentResult,
				Success:   true,
				InputData: templateVars,
			}
			eventBridge.HandleEvent(ctx, &baseevents.AgentEvent{
				Type:      orchestrator_events.OrchestratorAgentEnd,
				Timestamp: time.Now(),
				Data:      completedEvent,
			})
		}
	}

	return currentResult, currentConversationHistory, nil
}

// codeExecDebuggingSystemPromptProcessor creates the system prompt
func (agent *WorkflowCodeExecDebuggingAgent) codeExecDebuggingSystemPromptProcessor(templateVars map[string]string) string {
	var result strings.Builder
	if err := codeExecDebuggingSystemTemplate.Execute(&result, templateVars); err != nil {
		return "Error executing system prompt template: " + err.Error()
	}
	return result.String()
}

// codeExecDebuggingUserMessageProcessor creates the user message
func (agent *WorkflowCodeExecDebuggingAgent) codeExecDebuggingUserMessageProcessor(templateVars map[string]string) string {
	var result strings.Builder
	if err := codeExecDebuggingUserTemplate.Execute(&result, templateVars); err != nil {
		return "Error executing user message template: " + err.Error()
	}
	return result.String()
}
