import { describe, expect, it } from 'vitest'
import { normalizeProductChatFailure } from './productChatFailure'

describe('normalizeProductChatFailure gateway timeouts', () => {
  it('reports a CloudFront 504 as a slow server, not a configuration error', () => {
    const raw = 'Request failed with status code 504\n<H1>504 Gateway Timeout ERROR</H1>\nThe request could not be satisfied. There might be too much traffic or a configuration error.\nGenerated by cloudfront (CloudFront)'
    const failure = normalizeProductChatFailure(raw)
    expect(failure.title).toBe('The server took too long to respond')
    expect(failure.code).not.toBe('configuration_error')
    expect(failure.retryable).toBe(true)
  })

  it('still reports real configuration errors', () => {
    expect(normalizeProductChatFailure('MCP_API_URL is not configured').code).toBe('configuration_error')
  })
})
