apiVersion: v1
kind: Service
metadata:
  name: mcpagent-workspace-api-cs
  namespace: prod-mcpagent
  labels:
    app.kubernetes.io/name: cs
    app.kubernetes.io/instance: mcpagent-workspace-api
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: script
spec:
  selector:
    app.kubernetes.io/name: cs
    app.kubernetes.io/instance: mcpagent-workspace-api
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
