apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agent-db-pvc
  namespace: prod-mcpagent
  labels:
    app.kubernetes.io/name: cs
    app.kubernetes.io/instance: mcpagent-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
