apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-docs-pvc
  namespace: prod-mcpagent
  labels:
    app.kubernetes.io/name: cs
    app.kubernetes.io/instance: mcpagent-workspace-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
